mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
allow-lan: true
mode: Rule
geodata-mode: true
unified-delay: true
log-level: silent
ipv6: true
external-controller: 0.0.0.0:9090
#面板默认Meta 可选Yacd 清除浏览器缓存即可重新加载
external-ui: ./dashboard/Meta #Yacd
secret: ""
tcp-concurrent: true
enable-process: true
find-process-mode: strict
global-client-fingerprint: chrome

#####################
#修改配置文件时，建议先停止模块服务，再进行保存.
#####################

geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: false
  device: tun0
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
  
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - 'connect.rom.miui.com'
    - 'localhost.ptlogin2.qq.com'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    
  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - 1.主要地址
    - 2.备用地址

proxy-providers:
  1.主要地址:
    <<: *p
    url: "订阅地址1"
    path: ./proxy_providers/subscribe1.yaml
    #注意！如果您的订阅链接中带有“&”字符，请删掉.
  2.备用地址:
    <<: *p
    url: "订阅地址2"
    path: ./proxy_providers/subscribe2.yaml
    #注意！如果您的订阅链接中带有“&”字符，请删掉.
proxy-groups:
  - {name: 🎯 总模式, type: select, proxies: [🚀 节点选择,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3,🌎 直连]}
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 自动切换,🌎 直连], <<: *u}
  - {name: ♻️ 自动切换, <<: *u, tolerance: 2, type: url-test}
  - {name: ♻️ 手动切换1, type: select, proxies: [🚀 节点选择,🌎 直连], <<: *u}
  - {name: ♻️ 手动切换2, type: select, proxies: [🚀 节点选择,🌎 直连], <<: *u}
  - {name: ♻️ 手动切换3, type: select, proxies: [🚀 节点选择,🌎 直连], <<: *u}
  - {name: 🤖 OpenAI, type: select, proxies: [🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3,🌎 直连]}
  - {name: Ⓜ️ 微软Bing, type: select, proxies: [🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3,🌎 直连]}
  - {name: 🎶 Spotify, type: select, proxies: [🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3,🌎 直连]}
  - {name: Ⓜ️ 微软服务, type: select, proxies: [🌎 直连,🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3]}
  - {name: Ⓜ️ 微软云盘, type: select, proxies: [🌎 直连,🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3]}
  - {name: 📢 谷歌服务, type: select, proxies: [🎯 总模式,♻️ 自动切换,♻️ 手动切换1,♻️ 手动切换2,♻️ 手动切换3,🌎 直连]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT,🌎 直连]}
  - {name: 🐋 漏网之鱼, type: select, proxies: [🎯 总模式,🌎 直连]}
  - {name: 🌎 直连, type: select, proxies: [DIRECT]}
rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml"
    interval: 86400
  Onedrive:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Onedrive.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml"
    interval: 86400
  Bing:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Bing
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Bing.yaml"
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Spotify
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Spotify.yaml"
    interval: 86400
  Openai:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Openai.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Google.yaml
    url: "https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml"
    interval: 86400
rules:
  - RULE-SET,Bing,Ⓜ️ 微软Bing
  - RULE-SET,Openai,🤖 OpenAI
  - RULE-SET,Spotify,🎶 Spotify
  #- GEOSITE,category-ads-all,🛑 广告拦截
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Onedrive,Ⓜ️ 微软云盘
  - RULE-SET,Google,📢 谷歌服务
  - GEOSITE,CN,🌎 直连
  - GEOIP,private,🌎 直连,no-resolve
  - GEOIP,CN,🌎 直连,no-resolve
  - MATCH,🐋 漏网之鱼
