# By：Steve
# 最后一次更新：2024.01.20
# TG频道：https://t.me/st7eve
# 下载配置后,请手动添加机场订阅
# 下载链接：https://gh.surgee.me/https://raw.githubusercontent.com/zxfccmm4/Surge/main/StashProMax.yaml
# 找到 {远程订阅} 部分，将SF 里面的 "改成你的订阅" 替换为 自己的机场订阅链接  

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxy-providers:
  SF:
    type: http
    url: "https://igdux.top/~Clash"
    interval: 86400
    path: ./SF.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver-policy:
    'rule-set:CustomDirect':
      - "https://223.5.5.5/dns-query#🐼 CN"
      - "https://120.53.53.53/dns-query#🐼 CN"
    
    'rule-set:Microsoft':
      - "https://223.5.5.5/dns-query#🐼 CN"
      - "https://120.53.53.53/dns-query#🐼 CN"

    'rule-set:Onedrive':
      - "https://223.5.5.5/dns-query#🐼 CN"
      - "https://120.53.53.53/dns-query#🐼 CN"

    'rule-set:Copilot': 
      - "https://8.8.4.4/dns-query#🤖 Copilot"
      - "https://1.0.0.1/dns-query#🤖 Copilot"
   
    'rule-set:Gemini': 
      - "https://8.8.4.4/dns-query#🤖 Gemini"
      - "https://1.0.0.1/dns-query#🤖 Gemini"

    'rule-set:CustomProxy': 
      - "https://8.8.4.4/dns-query#♻️ Auto"
      - "https://1.0.0.1/dns-query#♻️ Auto"
    
    'rule-set:OpenAi': 
      - "https://8.8.4.4/dns-query#🤖 OpenAi"
      - "https://1.0.0.1/dns-query#🤖 OpenAi"

    'rule-set:Google': 
      - "https://8.8.4.4/dns-query#🚀 TopMode"
      - "https://1.0.0.1/dns-query#🚀 TopMode"

    'geosite:cn,private':
      - "https://223.5.5.5/dns-query#🐼 CN"
      - "https://120.53.53.53/dns-query#🐼 CN"
  
  nameserver:
    - "https://8.8.4.4/dns-query#♻️ Auto"
    - "https://1.0.0.1/dns-query#♻️ Auto"

  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query#🐼 CN"
    - "https://120.53.53.53/dns-query#🐼 CN"


proxy-groups:
  - {name: 🚀 TopMode, type: select, proxies: [♻️ Auto,🛠 Fallback,🔯 Load balancing,🌎 Select1,🌎 Select2,🌎 Select3,🐼 CN] }
  - {name: ♻️ Auto, <<: *u, tolerance: 2, type: url-test}
  - {name: 🌎 Select1, type: select, <<: *u}
  - {name: 🌎 Select2, type: select, <<: *u}
  - {name: 🌎 Select3, type: select, <<: *u}
  - {name: 🛠 Fallback, <<: *u, type: fallback, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: 🤖 OpenAi, type: select, proxies: [♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3]}
  - {name: 🤖 Copilot, type: select, proxies: [♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3]}
  - {name: 🤖 Gemini, type: select, proxies: [♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3]} 
  - {name: 🎶 Spotify, type: select, proxies: [♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3,🐼 CN]}
  - {name: Ⓜ️ Microsoft, type: select, proxies: [🐼 CN,♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3]}
  - {name: ☁ Onedrive, type: select, proxies: [🐼 CN,♻️ Auto,🌎 Select1,🌎 Select2,🌎 Select3]}
  - {name: 🔯 Load balancing, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: 🐼 CN, type: select, proxies: [DIRECT]}
  - {name: 🐋 Final, type: select, proxies: [🚀 TopMode]}
rule-providers:
  # 远程规则集
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    interval: 86400
  Onedrive:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Onedrive.yaml
    path: ./ruleset/Onedrive.yaml
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Copilot.yaml
    path: ./ruleset/Copilot.yaml
    interval: 86400
  OpenAi:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Openai.yaml
    path: ./ruleset/Openai.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Google.yaml
    path: ./ruleset/Google.yaml
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/RiverFlowsInUUU/Rule/main/magisk/Gemini.yaml
    path: ./ruleset/Gemini.yaml
    interval: 86400

rules:
  - GEOSITE,Telegram,🚀 TopMode
  - GEOSITE,Github,🚀 TopMode
  - GEOSITE,Spotify,🎶 Spotify
  - GEOSITE,Twitter,🚀 TopMode
  - RULE-SET,Copilot,🤖 Copilot
  - RULE-SET,Gemini,🤖 Gemini
  - RULE-SET,OpenAi,🤖 OpenAi
  - RULE-SET,Microsoft,Ⓜ️ Microsoft
  - RULE-SET,Onedrive,☁ Onedrive
  - RULE-SET,Google,🚀 TopMode
  - RULE-SET,CustomProxy,🚀 TopMode
  - RULE-SET,CustomDirect,🐼 CN
  - GEOSITE,CN,🐼 CN
  - GEOIP,private,🐼 CN
  - GEOIP,Telegram,🚀 TopMode
  - GEOIP,CN,🐼 CN
  - MATCH,🐋 Final
